### ISSUE TITLE
What are these "Keys" ?

### ISSUE THREAD

**Issue by EhsanFox** [svbnet/diezel#12]
~~I just wanted to say, is this `keys.json` required?~~
- ~~if yes,~~ where we should get and set these URL/Keys?

also, Great Work. I've been searching for such a package for a while now! 💖

**Comment by EhsanFox** [comment]
I know we should have them as you said in README.md, but a tip about "How to Find them?" is also useful and I would be grateful for that :)

**Comment by svbnet** [comment]
Ah. I should update the readme with a link to this Gist: https://gist.github.com/svbnet/b79b705a4c19d74896670c1ac7ad627e
