### ISSUE TITLE
MOBILE_GW_KEY

### ISSUE THREAD

**Issue by 89z** [svbnet/diezel#6]
I see a mention of this key, but its not provided, and its not explained how to get it. Can you elaborate?

https://github.com/svbnet/diezel/blob/9d82eb69c2887df0709cbc56d44f6532e4f2cda3/lib/clients/mobile-client.js#L38-L42

https://github.com/svbnet/diezel#mobileclient

**Comment by svbnet** [comment]
Please see here:
https://gist.github.com/svbnet/b79b705a4c19d74896670c1ac7ad627e
